# Generated by Django 5.0.2 on 2024-02-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
