# Generated by Django 5.0.2 on 2024-02-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_task_management', '0002_comment_state_role_state_task_state_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='stateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_task', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='estado',
        ),
        migrations.AddField(
            model_name='task',
            name='id_stateTask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado_tarea', to='advanced_task_management.statetask'),
            preserve_default=False,
        ),
    ]
